Update githooks

diff --git a/home/.githooks/bin/githooks b/home/.githooks/bin/githooks
--- a/home/.githooks/bin/githooks
+++ b/home/.githooks/bin/githooks
@@ -11,7 +11,7 @@
 # See the documentation in the project README for more information,
 #   or run the `git hooks help` command for available options.
 #
-# Version: 1908.261141-2cc7d9
+# Version: 1912.161811-71df49
 
 #####################################################
 # Prints the command line help for usage and
@@ -97,17 +97,26 @@ set_main_variables() {
 #####################################################
 # Checks if the current directory is
 #   a Git repository or not.
-#
+
 # Returns:
 #   0 if it is likely a Git repository,
 #   1 otherwise
 #####################################################
 is_running_in_git_repo_root() {
-    if ! git status >/dev/null 2>&1; then
-        return 1
-    fi
-
+    git rev-parse >/dev/null 2>&1 || return 1
     [ -d "${CURRENT_GIT_DIR}" ] || return 1
+}
+
+#####################################################
+# Echo if the current repository is non-bare.
+#
+# Returns: 0
+#####################################################
+echo_if_non_bare_repo() {
+    if [ "$(git rev-parse --is-bare-repository 2>/dev/null)" = "false" ]; then
+        echo "$@"
+    fi
+    return 0
 }
 
 #####################################################
@@ -121,6 +130,56 @@ is_running_in_git_repo_root() {
 #   0 on success, 1 when no hooks found
 #####################################################
 find_hook_path_to_enable_or_disable() {
+    if [ "$1" = "--shared" ]; then
+        shift
+
+        if [ -z "$1" ]; then
+            echo "For shared repositories, either the trigger type, the hook name or both needs to be given"
+            return 1
+        fi
+
+        if [ ! -d "$INSTALL_DIR/shared" ]; then
+            echo "No shared repositories found"
+            return 1
+        fi
+
+        for SHARED_ROOT in "$INSTALL_DIR/shared/"*; do
+            if [ ! -d "$SHARED_ROOT" ]; then
+                continue
+            fi
+
+            REMOTE_URL=$(cd "$SHARED_ROOT" && git config --get remote.origin.url)
+
+            SHARED_LOCAL_REPOS_LIST=$(grep -E "^[^#].+$" <"$(pwd)/.githooks/.shared")
+            ACTIVE_LOCAL_REPO=$(echo "$SHARED_LOCAL_REPOS_LIST" | grep -o "$REMOTE_URL")
+
+            ACTIVE_GLOBAL_REPO=$(git config --global --get githooks.shared | grep -o "$REMOTE_URL")
+
+            if [ "$ACTIVE_LOCAL_REPO" != "$REMOTE_URL" ] && [ "$ACTIVE_GLOBAL_REPO" != "$REMOTE_URL" ]; then
+                continue
+            fi
+
+            if [ -n "$1" ] && [ -n "$2" ]; then
+                if [ -f "$SHARED_ROOT/.githooks/$1/$2" ]; then
+                    HOOK_PATH="$SHARED_ROOT/.githooks/$1/$2"
+                    return
+                elif [ -f "$SHARED_ROOT/$1/$2" ]; then
+                    HOOK_PATH="$SHARED_ROOT/$1/$2"
+                    return
+                fi
+            elif [ -d "$SHARED_ROOT/.githooks" ]; then
+                HOOK_PATH=$(find "$SHARED_ROOT/.githooks" -name "$1" | head -1)
+                [ -n "$HOOK_PATH" ] && return 0 || return 1
+            else
+                HOOK_PATH=$(find "$SHARED_ROOT" -name "$1" | head -1)
+                [ -n "$HOOK_PATH" ] && return 0 || return 1
+            fi
+        done
+
+        echo "Sorry, cannot find any shared hooks that would match that"
+        return 1
+    fi
+
     if [ -z "$1" ]; then
         HOOK_PATH=$(cd .githooks && pwd)
 
@@ -200,9 +259,9 @@ disable_hook() {
     if [ "$1" = "help" ]; then
         print_help_header
         echo "
-git hooks disable [trigger] [hook-script]
-git hooks disable [hook-script]
-git hooks disable [trigger]
+git hooks disable [--shared] [trigger] [hook-script]
+git hooks disable [--shared] [hook-script]
+git hooks disable [--shared] [trigger]
 git hooks disable [-a|--all]
 git hooks disable [-r|--reset]
 
@@ -210,6 +269,9 @@ git hooks disable [-r|--reset]
     The \`trigger\` parameter should be the name of the Git event if given.
     The \`hook-script\` can be the name of the file to disable, or its
     relative path, or an absolute path, we will try to find it.
+    If the \`--shared\` parameter is given as the first argument,
+    hooks in the shared repositories will be disabled,
+    otherwise they are looked up in the current local repository.
     The \`--all\` parameter on its own will disable running any Githooks
     in the current repository, both existing ones and any future hooks.
     The \`--reset\` parameter is used to undo this, and let hooks run again.
@@ -274,14 +336,17 @@ enable_hook() {
     if [ "$1" = "help" ]; then
         print_help_header
         echo "
-git hooks enable [trigger] [hook-script]
-git hooks enable [hook-script]
-git hooks enable [trigger]
+git hooks enable [--shared] [trigger] [hook-script]
+git hooks enable [--shared] [hook-script]
+git hooks enable [--shared] [trigger]
 
     Enables a hook or hooks in the current repository.
     The \`trigger\` parameter should be the name of the Git event if given.
     The \`hook-script\` can be the name of the file to enable, or its
     relative path, or an absolute path, we will try to find it.
+    If the \`--shared\` parameter is given as the first argument,
+    hooks in the shared repositories will be enabled,
+    otherwise they are looked up in the current local repository.
 "
         return
     fi
@@ -318,14 +383,17 @@ accept_changes() {
     if [ "$1" = "help" ]; then
         print_help_header
         echo "
-git hooks accept [trigger] [hook-script]
-git hooks accept [hook-script]
-git hooks accept [trigger]
+git hooks accept [--shared] [trigger] [hook-script]
+git hooks accept [--shared] [hook-script]
+git hooks accept [--shared] [trigger]
 
     Accepts a new hook or changes to an existing hook.
     The \`trigger\` parameter should be the name of the Git event if given.
     The \`hook-script\` can be the name of the file to enable, or its
     relative path, or an absolute path, we will try to find it.
+    If the \`--shared\` parameter is given as the first argument,
+    hooks in the shared repositories will be accepted,
+    otherwise they are looked up in the current local repository.
 "
         return
     fi
@@ -336,6 +404,7 @@ git hooks accept [trigger]
     fi
 
     find_hook_path_to_enable_or_disable "$@" || exit 1
+
     ensure_checksum_file_exists
 
     find "$HOOK_PATH" -type f -path "*/.githooks/*" | while IFS= read -r HOOK_FILE; do
@@ -401,7 +470,7 @@ git hooks trust [forget]
             touch .githooks/trust-all &&
             git config githooks.trust.all Y &&
             echo "The current repository is now trusted." &&
-            echo "  Do not forget to commit and push the trust marker!" &&
+            echo_if_non_bare_repo "  Do not forget to commit and push the trust marker!" &&
             return
 
         echo "! Failed to mark the current repository as trusted" >&2
@@ -436,7 +505,7 @@ git hooks trust [forget]
     if [ "$1" = "delete" ] || [ -f .githooks/trust-all ]; then
         rm -rf .githooks/trust-all &&
             echo "The trust marker is removed from the repository." &&
-            echo "  Do not forget to commit and push the change!" &&
+            echo_if_non_bare_repo "  Do not forget to commit and push the change!" &&
             return
 
         echo "! Failed to delete the trust marker" >&2
@@ -859,7 +928,7 @@ add_shared_hook_repo() {
         echo "# Added on $(date)" >>"$(pwd)/.githooks/.shared" &&
             echo "$SHARED_REPO_URL" >>"$(pwd)/.githooks/.shared" &&
             echo "The new shared hook repository is successfully added" &&
-            echo "  Do not forget to commit the change!" &&
+            echo_if_non_bare_repo "  Do not forget to commit the change!" &&
             return
 
         echo "! Failed to add the new shared hook repository" >&2
@@ -962,7 +1031,7 @@ ${SHARED_REPO_ITEM}"
 
         echo "$NEW_LIST" >"$(pwd)/.githooks/.shared" &&
             echo "The list of shared hook repositories is successfully changed" &&
-            echo "  Do not forget to commit the change!" &&
+            echo_if_non_bare_repo "  Do not forget to commit the change!" &&
             return
 
         echo "! Failed to remove a shared hook repository" >&2
@@ -1192,7 +1261,7 @@ update_shared_hooks_in() {
 
         if [ -d "$SHARED_ROOT/.git" ]; then
             echo "* Updating shared hooks from: $SHARED_REPO"
-            PULL_OUTPUT=$(cd "$SHARED_ROOT" && git pull 2>&1)
+            PULL_OUTPUT="$(cd "$SHARED_ROOT" && git --work-tree="$SHARED_ROOT" --git-dir="$SHARED_ROOT/.git" -c core.hooksPath=/dev/null pull 2>&1)"
             # shellcheck disable=SC2181
             if [ $? -ne 0 ]; then
                 echo "! Update failed, git pull output:" >&2
@@ -1201,7 +1270,7 @@ update_shared_hooks_in() {
         else
             echo "* Retrieving shared hooks from: $SHARED_REPO"
             [ -d "$SHARED_ROOT" ] && rm -rf "$SHARED_ROOT"
-            CLONE_OUTPUT=$(git clone "$SHARED_REPO" "$SHARED_ROOT" 2>&1)
+            CLONE_OUTPUT=$(git -c core.hooksPath=/dev/null clone "$SHARED_REPO" "$SHARED_ROOT" 2>&1)
             # shellcheck disable=SC2181
             if [ $? -ne 0 ]; then
                 echo "! Clone failed, git clone output:" >&2
@@ -1653,7 +1722,8 @@ git hooks readme [add|update]
 
     mkdir -p "$(pwd)/.githooks" &&
         cat "$README_FILE" >"$(pwd)/.githooks/README.md" &&
-        echo "The README file is updated, do not forget to commit and push it!" ||
+        echo "The README file is updated." &&
+        echo_if_non_bare_repo "  Do not forget to commit and push it!" ||
         echo "! Failed to update the README file in the current repository" >&2
 }
 
@@ -1742,7 +1812,7 @@ git hooks ignore [trigger] [pattern...]
     done
 
     echo "The ignore file at $TARGET_DIR/.ignore is updated"
-    echo "  Do not forget to commit the changes!"
+    echo_if_non_bare_repo "  Do not forget to commit the changes!"
 }
 
 #####################################################
@@ -1821,6 +1891,14 @@ git hooks config [enable|disable|print] fail-on-non-existing-shared-hooks [--glo
 Enable or disable failing hooks with an error when any
 shared hooks configured in \`.shared\` are missing,
 which usually means \`git hooks update\` has not been called yet.
+
+git hooks config [yes|no|reset|print] delete-detected-lfs-hooks
+
+By default, detected LFS hooks during install are disabled and backed up.
+The \`yes\` option remembers to always delete these hooks. 
+The \`no\` option remembers the default behavior.
+The decision is reset with \`reset\` to the default behavior. 
+The \`print\` option outputs the current behavior.
 "
         return
     fi
@@ -1870,6 +1948,9 @@ which usually means \`git hooks update\` has not been called yet.
         ;;
     "fail-on-non-existing-shared-hooks")
         config_fail_on_not_existing_shared_hooks "$CONFIG_OPERATION" "$@"
+        ;;
+    "delete-detected-lfs-hooks")
+        config_delete_detected_lfs_hooks "$CONFIG_OPERATION" "$@"
         ;;
     *)
         manage_configuration "help"
@@ -2130,6 +2211,35 @@ config_fail_on_not_existing_shared_hooks() {
 
     else
         echo "! Invalid operation: \`$1\` (use \`enable\`, \`disable\` or \`print\`)" >&2
+        exit 1
+    fi
+}
+
+#####################################################
+# Manages the deleteDetectedLFSHooks default bahavior.
+# Modifies or prints
+#   `githooks.deleteDetectedLFSHooks`
+#   global Git configuration.
+#####################################################
+config_delete_detected_lfs_hooks() {
+    if [ "$1" = "yes" ]; then
+        git config --global githooks.deleteDetectedLFSHooks "a"
+        config_delete_detected_lfs_hooks "print"
+    elif [ "$1" = "no" ]; then
+        git config --global githooks.deleteDetectedLFSHooks "n"
+        config_delete_detected_lfs_hooks "print"
+    elif [ "$1" = "reset" ]; then
+        git config --global --unset githooks.deleteDetectedLFSHooks
+        config_delete_detected_lfs_hooks "print"
+    elif [ "$1" = "print" ]; then
+        VALUE=$(git config --global githooks.deleteDetectedLFSHooks)
+        if [ "$VALUE" = "Y" ]; then
+            echo "Detected LFS hooks are by default deleted"
+        else
+            echo "Detected LFS hooks are by default disabled and backed up"
+        fi
+    else
+        echo "! Invalid operation: \`$1\` (use \`yes\`, \`no\` or \`reset\`)" >&2
         exit 1
     fi
 }
