Update githooks

diff --git a/home/.githooks/bin/githooks b/home/.githooks/bin/githooks
--- a/home/.githooks/bin/githooks
+++ b/home/.githooks/bin/githooks
@@ -11,7 +11,7 @@
 # See the documentation in the project README for more information,
 #   or run the `git hooks help` command for available options.
 #
-# Version: 1908.051555-a42781
+# Version: 1908.261141-2cc7d9
 
 #####################################################
 # Prints the command line help for usage and
@@ -30,6 +30,7 @@ Available commands:
     list        Lists the active hooks in the current repository
     shared      Manages the shared hook repositories
     install     Installs the latest Githooks hooks
+    uninstall   Uninstalls the Githooks hooks
     update      Performs an update check
     readme      Manages the Githooks README in the current repository
     ignore      Manages Githooks ignore files in the current repository
@@ -53,19 +54,40 @@ print_help_header() {
 }
 
 #####################################################
+# Sets the ${INSTALL_DIR} variable.
+#
+# Returns: None
+#####################################################
+load_install_dir() {
+    INSTALL_DIR=$(git config --global --get githooks.installDir)
+
+    if [ -z "${INSTALL_DIR}" ]; then
+        # install dir not defined, use default
+        INSTALL_DIR=~/".githooks"
+    elif [ ! -d "$INSTALL_DIR" ]; then
+        echo "! Githooks installation is corrupt! " >&2
+        echo "  Install directory at ${INSTALL_DIR} is missing." >&2
+        INSTALL_DIR=~/".githooks"
+        echo "  Falling back to default directory at ${INSTALL_DIR}" >&2
+        echo "  Please run the Githooks install script again to fix it." >&2
+    fi
+}
+
+#####################################################
 # Set up the main variables that
 #   we will throughout the hook.
 #
 # Sets the ${CURRENT_GIT_DIR} variable
 #
-# Returns:
-#   None
+# Returns: None
 #####################################################
 set_main_variables() {
     CURRENT_GIT_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
     if [ "${CURRENT_GIT_DIR}" = "--git-common-dir" ]; then
         CURRENT_GIT_DIR=".git"
     fi
+
+    load_install_dir
 
     # Global IFS for loops
     IFS_COMMA_NEWLINE=",
@@ -670,19 +692,19 @@ get_hook_enabled_or_disabled_state() {
 
 #####################################################
 # List the shared hooks from the
-#   ~/.githooks/shared directory.
+#  $INSTALL_DIR/shared directory.
 #
 # Returns the list of paths to the hook files
 #   in the shared hook repositories found locally.
 #####################################################
 list_hooks_in_shared_repos() {
-    if [ ! -d ~/.githooks/shared ]; then
+    if [ ! -d "$INSTALL_DIR/shared" ]; then
         return
     fi
 
     SHARED_LIST_TYPE="$1"
 
-    for SHARED_ROOT in ~/.githooks/shared/*; do
+    for SHARED_ROOT in "$INSTALL_DIR/shared/"*; do
         if [ ! -d "$SHARED_ROOT" ]; then
             continue
         fi
@@ -749,8 +771,8 @@ git hooks shared [update|pull]
     fi
 
     if [ "$1" = "purge" ]; then
-        [ -w ~/.githooks/shared ] &&
-            rm -rf ~/.githooks/shared &&
+        [ -w "$INSTALL_DIR/shared" ] &&
+            rm -rf "$INSTALL_DIR/shared" &&
             echo "All existing shared hook repositories have been deleted locally" &&
             return
 
@@ -1148,7 +1170,7 @@ set_shared_root() {
     NORMALIZED_NAME=$(echo "$1" |
         sed -E "s#.*[:/](.+/.+)\\.git#\\1#" |
         sed -E "s/[^a-zA-Z0-9]/_/g")
-    SHARED_ROOT=~/.githooks/shared/"$NORMALIZED_NAME"
+    SHARED_ROOT="$INSTALL_DIR/shared/$NORMALIZED_NAME"
 }
 
 #####################################################
@@ -1164,7 +1186,7 @@ update_shared_hooks_in() {
     for SHARED_REPO in $SHARED_REPOS_LIST; do
         unset IFS
 
-        mkdir -p ~/.githooks/shared
+        mkdir -p "$INSTALL_DIR/shared"
 
         set_shared_root "$SHARED_REPO"
 
@@ -1236,6 +1258,48 @@ git hooks install [--global]
 
     if ! execute_install_script; then
         echo "! Failed to execute the installation" >&2
+        exit 1
+    fi
+}
+
+#####################################################
+# Executes an ondemand uninstallation of Githooks.
+#
+# Returns:
+#   1 if the uninstallation fails,
+#   0 otherwise
+#####################################################
+run_ondemand_uninstallation() {
+    if [ "$1" = "help" ]; then
+        print_help_header
+        echo "
+git hooks uninstall [--global]
+
+    Uninstalls the Githooks hooks from the current repository.
+    If the \`--global\` flag is given, it executes the uninstallation
+    globally, including the hook templates and all local repositories.
+"
+        return
+    fi
+
+    UNINSTALL_ARGS="--local"
+    if [ "$1" = "--global" ]; then
+        UNINSTALL_ARGS="--global"
+    elif [ -n "$1" ]; then
+        echo "! Invalid argument: \`$1\`" >&2 && exit 1
+    fi
+
+    echo "Fetching the uninstall script ..."
+
+    if ! fetch_latest_uninstall_script; then
+        echo "! Failed to fetch the latest uninstall script" >&2
+        echo "  You can retry manually using one of the alternative methods," >&2
+        echo "  see them here: https://github.com/rycus86/githooks#uninstalling" >&2
+        exit 1
+    fi
+
+    if ! execute_uninstall_script $UNINSTALL_ARGS; then
+        echo "! Failed to execute the uninstallation" >&2
         exit 1
     fi
 }
@@ -1329,12 +1393,12 @@ record_update_time() {
 #   `$1`
 #
 # Returns:
-#   0 and "~/.githooks/tools/$1/run"
+#   0 and "$INSTALL_DIR/tools/$1/run"
 #   1 and "" otherwise
 #####################################################
 get_tool_script() {
-    if [ -f ~/".githooks/tools/$1/run" ]; then
-        echo ~/".githooks/tools/$1/run" && return 0
+    if [ -f "$INSTALL_DIR/tools/$1/run" ]; then
+        echo "$INSTALL_DIR/tools/$1/run" && return 0
     fi
     return 1
 }
@@ -1402,7 +1466,7 @@ download_file() {
 
 #####################################################
 # Loads the contents of the latest install
-#   script into a variable.
+#   script into a file ${INSTALL_SCRIPT}.
 #
 # Sets the ${INSTALL_SCRIPT} variable
 #
@@ -1412,6 +1476,22 @@ download_file() {
 fetch_latest_install_script() {
     INSTALL_SCRIPT="$(mktemp)"
     if ! download_file "install.sh" "$INSTALL_SCRIPT"; then
+        return 1
+    fi
+}
+
+#####################################################
+# Loads the contents of the latest uninstall
+#   script into a file ${UNINSTALL_SCRIPT}.
+#
+# Sets the ${UNINSTALL_SCRIPT} variable
+#
+# Returns:
+#   1 if failed the load the script, 0 otherwise
+#####################################################
+fetch_latest_uninstall_script() {
+    UNINSTALL_SCRIPT="$(mktemp)"
+    if ! download_file "uninstall.sh" "$UNINSTALL_SCRIPT"; then
         return 1
     fi
 }
@@ -1482,6 +1562,28 @@ execute_install_script() {
         fi
     else
         if sh <"$INSTALL_SCRIPT"; then
+            return 0
+        fi
+    fi
+
+    return 1
+}
+
+#####################################################
+# Performs the uninstallation of the previously
+#   fetched uninstall script.
+#
+# Returns:
+#   0 if the uninstallation was successful,
+#   1 otherwise
+#####################################################
+execute_uninstall_script() {
+    if [ $# -ne 0 ]; then
+        if sh -s -- "$@" <"$UNINSTALL_SCRIPT"; then
+            return 0
+        fi
+    else
+        if sh <"$UNINSTALL_SCRIPT"; then
             return 0
         fi
     fi
@@ -2099,10 +2201,10 @@ git hooks tools unregister [download|dialog]
 
     case "$TOOLS_OPERATION" in
     "register")
-        tools_install "$@"
+        tools_register "$@"
         ;;
     "unregister")
-        tools_uninstall "$@"
+        tools_unregister "$@"
         ;;
     *)
         manage_tools "help"
@@ -2118,7 +2220,7 @@ git hooks tools unregister [download|dialog]
 # Returns:
 #   1 on failure, 0 otherwise
 #####################################################
-tools_install() {
+tools_register() {
     if [ "$1" = "download" ] || [ "$1" = "dialog" ]; then
         SCRIPT_FOLDER="$2"
 
@@ -2130,12 +2232,12 @@ tools_install() {
                 exit 1
             fi
 
-            if ! tools_uninstall "$1" --quiet; then
+            if ! tools_unregister "$1" --quiet; then
                 echo "! Unregister failed!" >&2
                 exit 1
             fi
 
-            TARGET_FOLDER=~/".githooks/tools/$1"
+            TARGET_FOLDER="$INSTALL_DIR/tools/$1"
 
             mkdir -p "$TARGET_FOLDER" >/dev/null 2>&1 # Install new
             if ! cp -r "$SCRIPT_FOLDER"/* "$TARGET_FOLDER"/; then
@@ -2159,12 +2261,12 @@ tools_install() {
 # Returns:
 #   1 on failure, 0 otherwise
 #####################################################
-tools_uninstall() {
+tools_unregister() {
     [ "$2" = "--quiet" ] && QUIET="Y"
 
     if [ "$1" = "download" ] || [ "$1" = "dialog" ]; then
-        if [ -d ~/".githooks/tools/$1" ]; then
-            rm -r ~/".githooks/tools/$1"
+        if [ -d "$INSTALL_DIR/tools/$1" ]; then
+            rm -r "$INSTALL_DIR/tools/$1"
             [ -n "$QUIET" ] || echo "Uninstalled the \`$1\` tool"
         else
             [ -n "$QUIET" ] || echo "! The \`$1\` tool is not installed" >&2
@@ -2237,6 +2339,9 @@ choose_command() {
     "install")
         run_ondemand_installation "$@"
         ;;
+    "uninstall")
+        run_ondemand_uninstallation "$@"
+        ;;
     "update")
         run_update_check "$@"
         ;;
@@ -2266,7 +2371,6 @@ choose_command() {
     esac
 }
 
-# Set the main variables we will need
 set_main_variables
 # Choose and execute the command
 choose_command "$@"
